//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fenix
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class FenixEntities : DbContext
    {
        public FenixEntities()
            : base("name=FenixEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual int prGetAppLogStatus(ObjectParameter returnValue, ObjectParameter returnMessage)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prGetAppLogStatus", returnValue, returnMessage);
        }
    
        public virtual int prGetAutomatStatus(ObjectParameter returnValue, ObjectParameter returnMessage)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prGetAutomatStatus", returnValue, returnMessage);
        }
    }
}
