//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fenix.FenixSoapService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SimpleResult", Namespace="http://www.upc.cz/fenixSoapWS")]
    [System.SerializableAttribute()]
    public partial class SimpleResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int NumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Number {
            get {
                return this.NumberField;
            }
            set {
                if ((this.NumberField.Equals(value) != true)) {
                    this.NumberField = value;
                    this.RaisePropertyChanged("Number");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SubmitDataToProcessingResult", Namespace="http://www.upc.cz/fenixSoapWS")]
    [System.SerializableAttribute()]
    public partial class SubmitDataToProcessingResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Fenix.FenixSoapService.Errors[] ErrorsField;
        
        private long MessageNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageDescriptionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public Fenix.FenixSoapService.Errors[] Errors {
            get {
                return this.ErrorsField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorsField, value) != true)) {
                    this.ErrorsField = value;
                    this.RaisePropertyChanged("Errors");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long MessageNumber {
            get {
                return this.MessageNumberField;
            }
            set {
                if ((this.MessageNumberField.Equals(value) != true)) {
                    this.MessageNumberField = value;
                    this.RaisePropertyChanged("MessageNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string MessageDescription {
            get {
                return this.MessageDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageDescriptionField, value) != true)) {
                    this.MessageDescriptionField = value;
                    this.RaisePropertyChanged("MessageDescription");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Errors", Namespace="http://www.upc.cz/fenixSoapWS")]
    [System.SerializableAttribute()]
    public partial class Errors : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ErrorCode {
            get {
                return this.ErrorCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorCodeField, value) != true)) {
                    this.ErrorCodeField = value;
                    this.RaisePropertyChanged("ErrorCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.upc.cz/fenixSoapWS", ConfigurationName="FenixSoapService.FenixSoapWebSvcSoap")]
    public interface FenixSoapWebSvcSoap {
        
        // CODEGEN: Generating message contract since element name login from namespace http://www.upc.cz/fenixSoapWS is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.upc.cz/fenixSoapWS/TSubmitDataToProcessing", ReplyAction="*")]
        Fenix.FenixSoapService.TSubmitDataToProcessingResponse TSubmitDataToProcessing(Fenix.FenixSoapService.TSubmitDataToProcessingRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.upc.cz/fenixSoapWS/TSubmitDataToProcessing", ReplyAction="*")]
        System.Threading.Tasks.Task<Fenix.FenixSoapService.TSubmitDataToProcessingResponse> TSubmitDataToProcessingAsync(Fenix.FenixSoapService.TSubmitDataToProcessingRequest request);
        
        // CODEGEN: Generating message contract since element name login from namespace http://www.upc.cz/fenixSoapWS is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.upc.cz/fenixSoapWS/SubmitDataToProcessing", ReplyAction="*")]
        Fenix.FenixSoapService.SubmitDataToProcessingResponse SubmitDataToProcessing(Fenix.FenixSoapService.SubmitDataToProcessingRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.upc.cz/fenixSoapWS/SubmitDataToProcessing", ReplyAction="*")]
        System.Threading.Tasks.Task<Fenix.FenixSoapService.SubmitDataToProcessingResponse> SubmitDataToProcessingAsync(Fenix.FenixSoapService.SubmitDataToProcessingRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TSubmitDataToProcessingRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TSubmitDataToProcessing", Namespace="http://www.upc.cz/fenixSoapWS", Order=0)]
        public Fenix.FenixSoapService.TSubmitDataToProcessingRequestBody Body;
        
        public TSubmitDataToProcessingRequest() {
        }
        
        public TSubmitDataToProcessingRequest(Fenix.FenixSoapService.TSubmitDataToProcessingRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.upc.cz/fenixSoapWS")]
    public partial class TSubmitDataToProcessingRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string login;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public TSubmitDataToProcessingRequestBody() {
        }
        
        public TSubmitDataToProcessingRequestBody(string login, string password) {
            this.login = login;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TSubmitDataToProcessingResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TSubmitDataToProcessingResponse", Namespace="http://www.upc.cz/fenixSoapWS", Order=0)]
        public Fenix.FenixSoapService.TSubmitDataToProcessingResponseBody Body;
        
        public TSubmitDataToProcessingResponse() {
        }
        
        public TSubmitDataToProcessingResponse(Fenix.FenixSoapService.TSubmitDataToProcessingResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.upc.cz/fenixSoapWS")]
    public partial class TSubmitDataToProcessingResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Fenix.FenixSoapService.SimpleResult TSubmitDataToProcessingResult;
        
        public TSubmitDataToProcessingResponseBody() {
        }
        
        public TSubmitDataToProcessingResponseBody(Fenix.FenixSoapService.SimpleResult TSubmitDataToProcessingResult) {
            this.TSubmitDataToProcessingResult = TSubmitDataToProcessingResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SubmitDataToProcessingRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SubmitDataToProcessing", Namespace="http://www.upc.cz/fenixSoapWS", Order=0)]
        public Fenix.FenixSoapService.SubmitDataToProcessingRequestBody Body;
        
        public SubmitDataToProcessingRequest() {
        }
        
        public SubmitDataToProcessingRequest(Fenix.FenixSoapService.SubmitDataToProcessingRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.upc.cz/fenixSoapWS")]
    public partial class SubmitDataToProcessingRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string login;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string partnerCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string messageType;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public byte[] data;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string encoding;
        
        public SubmitDataToProcessingRequestBody() {
        }
        
        public SubmitDataToProcessingRequestBody(string login, string password, string partnerCode, string messageType, byte[] data, string encoding) {
            this.login = login;
            this.password = password;
            this.partnerCode = partnerCode;
            this.messageType = messageType;
            this.data = data;
            this.encoding = encoding;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SubmitDataToProcessingResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SubmitDataToProcessingResponse", Namespace="http://www.upc.cz/fenixSoapWS", Order=0)]
        public Fenix.FenixSoapService.SubmitDataToProcessingResponseBody Body;
        
        public SubmitDataToProcessingResponse() {
        }
        
        public SubmitDataToProcessingResponse(Fenix.FenixSoapService.SubmitDataToProcessingResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.upc.cz/fenixSoapWS")]
    public partial class SubmitDataToProcessingResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Fenix.FenixSoapService.SubmitDataToProcessingResult SubmitDataToProcessingResult;
        
        public SubmitDataToProcessingResponseBody() {
        }
        
        public SubmitDataToProcessingResponseBody(Fenix.FenixSoapService.SubmitDataToProcessingResult SubmitDataToProcessingResult) {
            this.SubmitDataToProcessingResult = SubmitDataToProcessingResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface FenixSoapWebSvcSoapChannel : Fenix.FenixSoapService.FenixSoapWebSvcSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FenixSoapWebSvcSoapClient : System.ServiceModel.ClientBase<Fenix.FenixSoapService.FenixSoapWebSvcSoap>, Fenix.FenixSoapService.FenixSoapWebSvcSoap {
        
        public FenixSoapWebSvcSoapClient() {
        }
        
        public FenixSoapWebSvcSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FenixSoapWebSvcSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FenixSoapWebSvcSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FenixSoapWebSvcSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Fenix.FenixSoapService.TSubmitDataToProcessingResponse Fenix.FenixSoapService.FenixSoapWebSvcSoap.TSubmitDataToProcessing(Fenix.FenixSoapService.TSubmitDataToProcessingRequest request) {
            return base.Channel.TSubmitDataToProcessing(request);
        }
        
        public Fenix.FenixSoapService.SimpleResult TSubmitDataToProcessing(string login, string password) {
            Fenix.FenixSoapService.TSubmitDataToProcessingRequest inValue = new Fenix.FenixSoapService.TSubmitDataToProcessingRequest();
            inValue.Body = new Fenix.FenixSoapService.TSubmitDataToProcessingRequestBody();
            inValue.Body.login = login;
            inValue.Body.password = password;
            Fenix.FenixSoapService.TSubmitDataToProcessingResponse retVal = ((Fenix.FenixSoapService.FenixSoapWebSvcSoap)(this)).TSubmitDataToProcessing(inValue);
            return retVal.Body.TSubmitDataToProcessingResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Fenix.FenixSoapService.TSubmitDataToProcessingResponse> Fenix.FenixSoapService.FenixSoapWebSvcSoap.TSubmitDataToProcessingAsync(Fenix.FenixSoapService.TSubmitDataToProcessingRequest request) {
            return base.Channel.TSubmitDataToProcessingAsync(request);
        }
        
        public System.Threading.Tasks.Task<Fenix.FenixSoapService.TSubmitDataToProcessingResponse> TSubmitDataToProcessingAsync(string login, string password) {
            Fenix.FenixSoapService.TSubmitDataToProcessingRequest inValue = new Fenix.FenixSoapService.TSubmitDataToProcessingRequest();
            inValue.Body = new Fenix.FenixSoapService.TSubmitDataToProcessingRequestBody();
            inValue.Body.login = login;
            inValue.Body.password = password;
            return ((Fenix.FenixSoapService.FenixSoapWebSvcSoap)(this)).TSubmitDataToProcessingAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Fenix.FenixSoapService.SubmitDataToProcessingResponse Fenix.FenixSoapService.FenixSoapWebSvcSoap.SubmitDataToProcessing(Fenix.FenixSoapService.SubmitDataToProcessingRequest request) {
            return base.Channel.SubmitDataToProcessing(request);
        }
        
        public Fenix.FenixSoapService.SubmitDataToProcessingResult SubmitDataToProcessing(string login, string password, string partnerCode, string messageType, byte[] data, string encoding) {
            Fenix.FenixSoapService.SubmitDataToProcessingRequest inValue = new Fenix.FenixSoapService.SubmitDataToProcessingRequest();
            inValue.Body = new Fenix.FenixSoapService.SubmitDataToProcessingRequestBody();
            inValue.Body.login = login;
            inValue.Body.password = password;
            inValue.Body.partnerCode = partnerCode;
            inValue.Body.messageType = messageType;
            inValue.Body.data = data;
            inValue.Body.encoding = encoding;
            Fenix.FenixSoapService.SubmitDataToProcessingResponse retVal = ((Fenix.FenixSoapService.FenixSoapWebSvcSoap)(this)).SubmitDataToProcessing(inValue);
            return retVal.Body.SubmitDataToProcessingResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Fenix.FenixSoapService.SubmitDataToProcessingResponse> Fenix.FenixSoapService.FenixSoapWebSvcSoap.SubmitDataToProcessingAsync(Fenix.FenixSoapService.SubmitDataToProcessingRequest request) {
            return base.Channel.SubmitDataToProcessingAsync(request);
        }
        
        public System.Threading.Tasks.Task<Fenix.FenixSoapService.SubmitDataToProcessingResponse> SubmitDataToProcessingAsync(string login, string password, string partnerCode, string messageType, byte[] data, string encoding) {
            Fenix.FenixSoapService.SubmitDataToProcessingRequest inValue = new Fenix.FenixSoapService.SubmitDataToProcessingRequest();
            inValue.Body = new Fenix.FenixSoapService.SubmitDataToProcessingRequestBody();
            inValue.Body.login = login;
            inValue.Body.password = password;
            inValue.Body.partnerCode = partnerCode;
            inValue.Body.messageType = messageType;
            inValue.Body.data = data;
            inValue.Body.encoding = encoding;
            return ((Fenix.FenixSoapService.FenixSoapWebSvcSoap)(this)).SubmitDataToProcessingAsync(inValue);
        }
    }
}
