//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FenixControl.SmsSend {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SmsSend.SmsSendSoap")]
    public interface SmsSendSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendNotification", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SendNotification(string phoneNumbers, string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendNotification", ReplyAction="*")]
        System.Threading.Tasks.Task<string> SendNotificationAsync(string phoneNumbers, string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendNotificationFromSender", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SendNotificationFromSender(string phoneNumbers, string data, string sender);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendNotificationFromSender", ReplyAction="*")]
        System.Threading.Tasks.Task<string> SendNotificationFromSenderAsync(string phoneNumbers, string data, string sender);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendMessage", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode SendMessage(string phoneNumbers, string accountNumber, string message, string sender, string senderId, string onTime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendMessage", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> SendMessageAsync(string phoneNumbers, string accountNumber, string message, string sender, string senderId, string onTime);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SmsSendSoapChannel : FenixControl.SmsSend.SmsSendSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SmsSendSoapClient : System.ServiceModel.ClientBase<FenixControl.SmsSend.SmsSendSoap>, FenixControl.SmsSend.SmsSendSoap {
        
        public SmsSendSoapClient() {
        }
        
        public SmsSendSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SmsSendSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SmsSendSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SmsSendSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string SendNotification(string phoneNumbers, string data) {
            return base.Channel.SendNotification(phoneNumbers, data);
        }
        
        public System.Threading.Tasks.Task<string> SendNotificationAsync(string phoneNumbers, string data) {
            return base.Channel.SendNotificationAsync(phoneNumbers, data);
        }
        
        public string SendNotificationFromSender(string phoneNumbers, string data, string sender) {
            return base.Channel.SendNotificationFromSender(phoneNumbers, data, sender);
        }
        
        public System.Threading.Tasks.Task<string> SendNotificationFromSenderAsync(string phoneNumbers, string data, string sender) {
            return base.Channel.SendNotificationFromSenderAsync(phoneNumbers, data, sender);
        }
        
        public System.Xml.XmlNode SendMessage(string phoneNumbers, string accountNumber, string message, string sender, string senderId, string onTime) {
            return base.Channel.SendMessage(phoneNumbers, accountNumber, message, sender, senderId, onTime);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> SendMessageAsync(string phoneNumbers, string accountNumber, string message, string sender, string senderId, string onTime) {
            return base.Channel.SendMessageAsync(phoneNumbers, accountNumber, message, sender, senderId, onTime);
        }
    }
}
